# Candace Savonen Mar 2022

name: Testing ottr-reports
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:

  get_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Branch used
      id: extract_branch
      run: echo "branch=$(echo ${GITHUB_REF##*/})" >> $GITHUB_OUTPUT

  spell-check:
    needs: get_branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v3

    - name: Check spelling
      id: check_spelling
      uses: ./
      with:
        check_type: spelling
        error_min: 3
        branch_name: ${{ steps.extract_branch.outputs.branch }}

    - name: Find outputs
      run: |
        echo ${{ steps.check_spelling.outputs.report_path }}
        cat ${{ steps.check_spelling.outputs.report_path }}
        echo ${{ steps.check_spelling.outputs.error_num}}
      shell: bash

  urls-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v3

    - name: Check URLs
      id: check_urls
      uses: ./
      with:
        check_type: urls
        error_min: 0
        branch_name: ${{ steps.extract_branch.outputs.branch }}

    - name: Find outputs
      run: |
        echo ${{ steps.check_urls.outputs.report_path }}
        cat ${{ steps.check_urls.outputs.report_path }}
        echo ${{ steps.check_urls.outputs.error_num}}
      shell: bash

  quiz-format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v3

    - name: Check quiz formatting
      id: quiz_format
      uses: ./
      with:
        check_type: quiz_format
        error_min: 0
        branch_name: ${{ steps.extract_branch.outputs.branch }}

    - name: Find outputs
      run: |
        echo ${{ steps.quiz_format.outputs.report_path }}
        cat ${{ steps.quiz_format.outputs.report_path }}
        echo ${{ steps.quiz_format.outputs.error_num}}
      shell: bash
